language: d
sudo: false

before_script:
    - dub add-local .

matrix:
    include:
        - d: dmd
        - d: dmd-2.079.0
        - d: dmd-2.078.2
        - d: dmd-2.077.1
        - d: dmd-2.076.1
        - d: dmd-2.075.1
        - d: dmd-2.074.1
        - d: dmd-2.073.1
        - d: dmd-2.072.2
        - d: dmd-2.071.2
        - d: dmd-2.070.2
        - d: dmd-2.069.2
        - d: dmd-2.068.1
        - d: dmd-2.068.0
        - d: dmd-2.067.1
        - d: dmd-2.067.0
        - d: dmd-2.066.1
        - d: dmd-2.066.0
        - d: ldc-1.7.0
        - d: ldc-1.6.0
        - d: ldc-1.5.0
        - d: ldc-1.4.0
        - d: ldc-1.3.0
        - d: ldc-1.2.0
        - d: ldc-1.1.1
        - d: ldc-1.1.0
        - d: ldc-1.0.0
        - d: ldc-0.17.1
        - d: ldc-0.16.1
        - d: ldc-0.15.1
        - d: gdc-5.2.0
        - d: gdc-4.9.3
        - d: gdc-4.9.2
        - d: gdc-4.8.5
