platform: x64
environment:
 matrix:
  #- DC: dmd
  #  DVersion: 2.079.1
  #  arch: x64
  #- DC: dmd
  #  DVersion: 2.078.3
  #  arch: x64
  #- DC: dmd
  #  DVersion: 2.077.1
  #  arch: x64
  #- DC: dmd
  #  DVersion: 2.076.1
  #  arch: x64
  #- DC: dmd
  #  DVersion: 2.075.1
  #  arch: x64
  #- DC: dmd
  #  DVersion: 2.074.1
  #  arch: x64
  #- DC: dmd
  #  DVersion: 2.073.2
  #  arch: x64
  #- DC: dmd
  #  DVersion: 2.072.2
  #  arch: x64
  #- DC: dmd
  #  DVersion: 2.071.2
  #  arch: x64
  #- DC: dmd
  #  DVersion: 2.070.2
  #  arch: x64
  #- DC: dmd
  #  DVersion: 2.069.2
  #  arch: x64
  #- DC: dmd
  #  DVersion: 2.068.2
  #  arch: x64
  #- DC: dmd
  #  DVersion: 2.067.1
  #  arch: x64
  #- DC: dmd
  #  DVersion: 2.066.0
  #  arch: x64
  - DC: ldc
    DVersion: 1.7.0
    arch: x64
  - DC: ldc
    DVersion: 1.6.0
    arch: x64
  - DC: ldc
    DVersion: 1.5.0
    arch: x64
  - DC: ldc
    DVersion: 1.4.0
    arch: x64
  - DC: ldc
    DVersion: 1.3.0
    arch: x64
  - DC: ldc
    DVersion: 1.2.0
    arch: x64
  - DC: ldc
    DVersion: 1.1.0
    arch: x64
  - DC: ldc
    DVersion: 1.0.0
    arch: x64
  - DC: ldc
    DVersion: 0.17.1
    arch: x64
  - DC: ldc
    DVersion: 0.16.1
    arch: x64

skip_tags: true

install:
  - ps: function SetUpDCompiler
        {
            if($env:DC -eq "dmd"){
              if($env:arch -eq "x86"){
                $env:DConf = "m32";
              }
              elseif($env:arch -eq "x64"){
                $env:DConf = "m64";
              }
              echo "downloading ...";
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "http://downloads.dlang.org/releases/2.x/$($version)/dmd.$($version).windows.zip" -OutFile "c:\dmd.zip";
              echo "finished.";
              pushd c:\\;
              7z x dmd.zip > $null;
              popd;
            }
            elseif($env:DC -eq "ldc"){
              echo "downloading ...";
              if($env:arch -eq "x86"){
                $env:DConf = "m32";
              }
              elseif($env:arch -eq "x64"){
                $env:DConf = "m64";
              }
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              $ldcArchive = "ldc.7z";
              try{
                Invoke-WebRequest "https://github.com/ldc-developers/ldc/releases/download/v$($version)/ldc2-$($version)-windows-x64.7z" -OutFile "c:\ldc.7z";
              }
              catch [Net.WebException]{
                Invoke-WebRequest "https://github.com/ldc-developers/ldc/releases/download/v$($version)/ldc2-$($version)-win64-msvc.zip" -OutFile "c:\ldc.zip";
                $ldcArchive = "ldc.zip";
              }
              echo "finished.";
              pushd c:\\;
              7z x $ldcArchive > $null;
              popd;
            }
        }
  - ps: SetUpDCompiler
  - powershell -Command Invoke-WebRequest https://code.dlang.org/files/dub-1.9.0-windows-x86.zip -OutFile dub.zip
  - 7z x dub.zip -odub > nul
  - set PATH=%CD%\%binpath%;%CD%\dub;%PATH%
  - dub --version

before_build:
  - ps: if($env:arch -eq "x86"){
            $env:compilersetupargs = "x86";
            $env:Darch = "x86";
          }
        elseif($env:arch -eq "x64"){
            $env:compilersetupargs = "amd64";
            $env:Darch = "x86_64";
        }
  - ps : if($env:DC -eq "dmd"){
           $env:PATH += ";C:\dmd2\windows\bin;";
           $env:DMD = "dmd";
         }
         elseif($env:DC -eq "ldc"){
           $version = $env:DVersion;
           $env:PATH += ";C:\ldc2-$($version)-windows-x64\bin";
           $env:DC = "ldmd2";
           $env:DMD = "ldmd2";
         }
  - ps: $env:compilersetup = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall";
  - '"%compilersetup%" %compilersetupargs%'

build_script:
 - echo dummy build script - dont remove me

test_script:
 - echo %PLATFORM%
 - echo %Darch%
 - echo %DC%
 - echo %DMD%
 - echo %PATH%
 - '%DC% --help'
 - dub add-local .
 - dub test --arch=%Darch% --compiler=%DC%
