#!/bin/sh

# 'ddox' must be installed and on PATH:
# https://github.com/rejectedsoftware/ddox

rdmd -Isrc --build-only --force -c -Dddocs_tmp -X -Xfdocs/docs.json src/scriptlike/package.d
rm -rf docs_tmp
rm src/scriptlike/package
ddox filter docs/docs.json --min-protection=Protected
ddox generate-html docs/docs.json docs/public --navigation-type=ModuleTree
